[theme]

# Primary accent for interactive elements
primaryColor = '#FFFAF0'

# Background color for the main content area
backgroundColor = '#F5FFFA'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFFFF0'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"